"""Cave generation module using a cellular automaton."""

import random

from core.base_field import BaseField
from utils.config import (
    BIRTH_DEATH_LIMITS,
    DEFAULT_BIRTH_LIMIT,
    DEFAULT_DEATH_LIMIT,
    DEFAULT_INIT_CHANCE,
)


class Cave(BaseField):
    """A cave generated by a cellular automaton.

    The field is encoded as a matrix: 1 — live (filled) cell,
    0 — dead (empty) cell.
    Cells outside the field boundary are considered alive (per the task spec).

    Attributes:
        field: cell state matrix (0/1).
        init_chance: initial fill probability of a cell (0-100).
        birth_limit: birth threshold for a dead cell (0-7).
        death_limit: death threshold for a live cell (0-7).
    """

    field: list[list[int]]
    init_chance: int
    birth_limit: int
    death_limit: int

    def __init__(
        self,
        rows: int = 0,
        cols: int = 0,
        field_mtx: list[list[int]] | None = None,
        init_chance: int = DEFAULT_INIT_CHANCE,
        birth_limit: int | None = None,
        death_limit: int | None = None,
    ) -> None:
        """Creates a cave of the given size.

        If ``field_mtx`` is None the field is filled randomly according to
        ``init_chance``; otherwise the provided matrix is validated and used.

        Args:
            rows: Number of rows.
            cols: Number of columns.
            field_mtx: Pre-built cell matrix (0/1), or None for random fill.
            init_chance: Probability (0–100 %) of a cell being alive at init.
            birth_limit: Dead cell becomes alive when live-neighbour count
                exceeds this value, i.e. ``neighbours > birth_limit``
                (defaults to ``DEFAULT_BIRTH_LIMIT``).
            death_limit: Minimum live-neighbour count for a live cell to
                survive (defaults to ``DEFAULT_DEATH_LIMIT``).

        Raises:
            ValueError: If dimensions are out of range, limits are invalid,
                or ``field_mtx`` contains values other than 0 and 1.
        """
        super().__init__(rows, cols)

        self.field = self._init_field(field_mtx)
        self.init_chance = init_chance
        self.birth_limit = (
            birth_limit if birth_limit is not None else DEFAULT_BIRTH_LIMIT
        )
        self.death_limit = (
            death_limit if death_limit is not None else DEFAULT_DEATH_LIMIT
        )

        self._validate_limits()
        if self.is_empty():
            self.generate_rand_field()
        self._validate_field()

    def _validate_limits(self) -> None:
        """Validates that the limits are valid."""
        if not self._check_limit(self.birth_limit):
            raise ValueError(f"Birth limit {self.birth_limit} is invalid")
        if not self._check_limit(self.death_limit):
            raise ValueError(f"Death limit {self.death_limit} is invalid")

    @staticmethod
    def _check_limit(value: int) -> bool:
        """Returns True if ``value`` is a valid birth/death limit (0–7)."""
        return value in BIRTH_DEATH_LIMITS

    def __repr__(self) -> str:
        """Returns a detailed string representation of the cave
        for debugging."""
        return (
            f"Cave(rows={self.rows}, cols={self.cols}, "
            f"field={self.field}, birth_limit={self.birth_limit}, "
            f"death_limit={self.death_limit})"
        )

    def __str__(self) -> str:
        """Returns a human-readable text map of the cave via ``visualize()``."""
        return self.visualize()

    def visualize(self) -> str:
        """Returns a bordered ASCII map of the cave.

        Live cells are shown as ``#``, dead cells as a space.
        Returns ``'Empty cave'`` for a 0×0 field.
        """
        if self.rows == 0 or self.cols == 0:
            return "Empty cave"

        EMPTY = " "
        FILLED = "#"
        BORDER = "─" * (self.cols * 2 + 1)

        result = []
        result.append(f"┌{BORDER}┐")

        for row in self.field:
            line = (
                "│ "
                + " ".join([EMPTY if cell == 0 else FILLED for cell in row])
                + " │"
            )
            result.append(line)

        result.append(f"└{BORDER}┘")
        return "\n".join(result)

    def get_field(self) -> list[list[int]]:
        """Returns a copy of the field."""
        return [row[:] for row in self.field]

    def get_init_chance(self) -> int:
        """Returns the initial live-cell probability (0–100 %)."""
        return self.init_chance

    def get_death_limit(self) -> int:
        """Returns the current cell death threshold."""
        return self.death_limit

    def get_birth_limit(self) -> int:
        """Returns the current cell birth threshold."""
        return self.birth_limit

    def _validate_field(self) -> None:
        """Checks that the field contains only 0s and 1s."""
        for line in self.field:
            for cell in line:
                if cell not in (0, 1):
                    raise ValueError("Invalid cell in field.")

    def is_empty(self) -> bool:
        """Checks whether the field is uninitialized (no rows)."""
        return not self.field

    def generate_rand_field(self) -> None:
        """
        Generates a random field of the specified size.
        """
        self.field = [
            [
                1 if random.random() * 100 < self.init_chance else 0
                for _ in range(self.cols)
            ]
            for _ in range(self.rows)
        ]

    @staticmethod
    def _is_out_of_axis(coordinate: int, max_coordinate: int) -> bool:
        """Is the coordinate outside the field boundary?"""
        return coordinate < 0 or coordinate >= max_coordinate

    def _is_out_of_field(self, row: int, col: int) -> bool:
        """
        Is the point outside the field boundary?
        Per the task spec: cells outside the boundary are considered alive.
        """
        return self._is_out_of_axis(row, self.rows) or self._is_out_of_axis(
            col, self.cols
        )

    def count_alive_neighbors(self, row: int, col: int) -> int:
        """Counts the number of live neighbours around a cell."""
        count = 0
        for dr in [-1, 0, 1]:
            for dc in [-1, 0, 1]:
                if dr == 0 and dc == 0:
                    continue

                r = row + dr
                c = col + dc

                # If the cell is outside the boundary, count it
                # as alive (per the task spec)
                if self._is_out_of_field(r, c) or self.field[r][c] == 1:
                    count += 1

        return count

    def next_generation(self) -> "Cave":
        """
        Creates a new cave — the next generation of the cellular automaton.
        1 = live cell, 0 = dead cell.
        Returns a new Cave object without modifying the current one.
        """
        new_field = [[0] * self.cols for _ in range(self.rows)]

        for i in range(self.rows):
            for j in range(self.cols):
                alive_neighbors = self.count_alive_neighbors(
                    i, j
                )  # number of live (1) neighbours

                if self.field[i][j] == 1:  # Live cell
                    # Dies (becomes dead) if live neighbours < death_limit
                    if alive_neighbors < self.death_limit:
                        new_field[i][j] = 0  # becomes dead
                    else:
                        new_field[i][j] = 1  # stays alive

                else:  # Dead cell (0)
                    # Born (becomes live) if live neighbours > birth_limit
                    if alive_neighbors > self.birth_limit:
                        new_field[i][j] = 1  # becomes alive
                    else:
                        new_field[i][j] = 0  # stays dead

        return Cave(
            rows=self.rows,
            cols=self.cols,
            field_mtx=new_field,
            init_chance=self.init_chance,
            birth_limit=self.birth_limit,
            death_limit=self.death_limit,
        )

    def is_final_generation(self) -> bool:
        """Checks whether the cave will change on the next step."""
        next_cave = self.next_generation()
        return self.field == next_cave.field
